(function($){$('html').removeClass('no-js');if($('.page').hasClass('fixed-header')){var didScroll;var lastScrollTop=0;var delta=$('div.page').attr('data-offset');var navbarHeight=$('.header').outerHeight();$("#toggle").change(function(){$('body').toggleClass('menu-open')});$(window).scroll(function(event){didScroll=!0});setInterval(function(){if(didScroll){hasScrolled();didScroll=!1}},250);function hasScrolled(){var st=$(this).scrollTop();if(Math.abs(lastScrollTop-st)<=delta)
    return;if(st>lastScrollTop&&st>navbarHeight){$('.header').removeClass('down').addClass('up');$('.main-menu .menu-item-has-children > a').attr('aria-expanded','false').next().slideUp(250)}else{if(st+$(window).height()<$(document).height()){$('.header').removeClass('up').addClass('down')}}
    lastScrollTop=st}
    $('.main-menu .menu-item-has-children > a').click(function(e){e.preventDefault();if($(e.target).attr('aria-expanded')=='false'){$('.main-menu .menu-item-has-children > a').attr('aria-expanded','false').next().slideUp(250);$(e.target).attr('aria-expanded','true').next().slideDown(250)}else{$(e.target).attr('aria-expanded','false').next().slideUp(250)}});$(window).resize(function(){var resize=!0;menuMedium(resize);stageColumn(resize);cookieText(resize)});function menuMedium(resize){if($('.main-menu')[0].scrollWidth>$('.main-menu').innerWidth()){if($('body').innerWidth()>=768){$('.main-menu li a').each(function(){var abbrevTitle=$(this).attr('data-abbrev');if(abbrevTitle!==undefined){$(this).text(abbrevTitle)}})}}
    else{if($('body').innerWidth()<=767){if(resize==!0){$('.main-menu > li > a').each(function(k,i){var abbrevTitle=$(this).attr('data-abbrev');var origTitle=$(this).attr('data-orig');if($(this).text()!==origTitle){$(this).text(origTitle)}})}}
    else{if(resize==!0){if($('body').innerWidth()>=1120){$('.main-menu > li > a').each(function(k,i){var abbrevTitle=$(this).attr('data-abbrev');var origTitle=$(this).attr('data-orig');if($(this).text()!==origTitle){$(this).text(origTitle)}})}}}}}
    menuMedium()}
    var bar_state=$.cookie('cookie_bar_hide');if(bar_state!=="hidden"){$('.cookies').show;$.cookie('cookie_bar_hide','visible',{path:'/'})}else{$('.cookies').hide;$.cookie('cookie_bar_hide','hidden',{path:'/'})}
    $('.hide').click(function(){$('.cookies').slideUp(250);$.removeCookie('cookie_bar_hide');$(".page").removeClass('has-cookie-bar');$.cookie('cookie_bar_hide','hidden',{path:'/'});return!1});if($.cookie("cookie_bar_hide")!=='visible'){$(".cookies").hide();$(".page").removeClass('has-cookie-bar')}
    function cookieText(resize){if($('body').innerWidth()<500){var smText=$('.cookies .textwidget').attr('data-small');var currentText=$('.cookies .textwidget > span').text();if(smText!==currentText){$('.cookies .textwidget > span').text(smText)}}
    else{var lgText=$('.cookies .textwidget').attr('data-big');var currentText=$('.cookies .textwidget > span').text();if(lgText!==currentText){$('.cookies .textwidget > span').text(lgText)}}}
    cookieText();$('.mediator-profile .full-profile').addClass('hidden');$('.mediator-profile .button').click(function(e){e.preventDefault();$(this).parents().next().removeClass('hidden');$(this).remove()});function stageColumn(resize){if($('body').innerWidth()>=980){var maxHeight=Math.max.apply(Math,$('.columns.stage').map(function(i,elem){return $(elem).height()}));if($('body').hasClass('home')){maxHeight=maxHeight+30}
    $('.columns.stage').height(maxHeight)}else{$('.columns.stage').css('height','auto')}}
    if($('.page:not(.lazyloading)')){stageColumn()}
    if($('.page').hasClass('lazyloading')){$("img.lazy").lazyload({load:lazyColumns})}
    function lazyColumns(element,el_left,settings){$(this).removeClass("loading-icon");stageColumn()}})(jQuery)